import React, { Component } from "react";

const Context = React.createContext();

export class Provider extends Component {
  handler = (action, newObject) => {
    switch (action) {
      case "ADD_EVENT":
        this.setState({
          events: [newObject, ...this.state.events],
        });
        break;
      case "ADD_REGIONAL_OFFICE":
        this.setState({
          regionalOffices: [newObject, ...this.state.regionalOffices],
        });
        break;
      default:
        break;
    }
  };

  state = {
    handler: this.handler,
    events:[
      {
        eid:"1",
        ename: "Event 1",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-08-12',
        etime: "12:10",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "2",
        rname: "Bengaluru",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",
        elikes:"2",
        estatus:'n',
      },
      {
        eid:"2",
        ename: "Event 2",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-08-12',
        etime: "12:00",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "8",
        rname: "Mumbai",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",
        elikes:"12",
        estatus:'y',
      },
      {
        eid:"3",
        ename: "Event 3",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-08-12',
        etime: "12:20",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "8",
        rname: "Mumbai",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"30",
         estatus:'n',
      },
      {
        eid:"4",
        ename: "Event 4",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-08-12',
        etime: "12:10",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "8",
        rname: "Mumbai",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'n',
      },
      {
        eid:"5",
        ename: "Event 5",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-09-22',
        etime: "11:00",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "8",
        rname: "Mumbai",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'n',
        },
      {
        eid:"6",
        ename: "Event 6",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-07-17',
        etime: "12:00",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "8",
        rname: "Mumbai",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'n',
      },
      {
        eid:"7",
        ename: "Event 7",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-07-27',
        etime: "12:00",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "8",
        rname: "Mumbai",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"21",
         estatus:'n',
      },
      {
        eid:"8",
        ename: "Event 8",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-09-22',
        etime: "12:00",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "8",
        rname: "Mumbai",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'n',
      },
      {
        eid:"9",
        ename: "Event 9",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-07-27',
        etime: "12:00",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "8",
        rname: "Mumbai",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'n',
      },
      {
        eid:"10",
        ename: "Event 10",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-07-18',
        etime: "12:00",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "8",
        rname: "Mumbai",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'n',
      },
      {
        eid:"11",
        ename: "Event 11",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-08-06',
        etime: "12:00",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "2",
        rname: "Bengaluru",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'n',
      },
      {
        eid:"12",
        ename: "Event 12",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-07-28',
        etime: "12:00",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "1",
        rname: "Ahmedabad",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'y',
      },
      {
        eid:"13",
        ename: "Event 13",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-07-17',
        etime: "12:00",
         
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "1",
        rname: "Ahmedabad",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'y',
      },
      {
        eid:"14",
        ename: "Event 14",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-07-30',
        etime: "12:00",
         
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "1",
        rname: "Ahmedabad",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'y',
      },
      {
        eid:"15",
        ename: "Event 15",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-07-22',
        etime: "12:00",
         
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "1",
        rname: "Ahmedabad",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'y',
      },
      {
        eid:"16",
        ename: "Event 16",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-07-17',
        etime: "12:00",
         
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "1",
        rname: "Ahmedabad",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'y',
      },
      {
        eid:"17",
        ename: "Event 17",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-07-27',
        etime: "12:00",
         
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "1",
        rname: "Ahmedabad",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'y',
      },
      {
        eid:"18",
        ename: "Event 18",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-07-22',
        etime: "12:00",
         
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "1",
        rname: "Ahmedabad",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'y',
      },
      {
        eid:"19",
        ename: "Event 19",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-07-27',
        etime: "12:00",
         
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "1",
        rname: "Ahmedabad",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'y',
      },
      {
        eid:"20",
        ename: "Event 20",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-07-18',
        etime: "12:00",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "1",
        rname: "Ahmedabad",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'y',
      },
      {
        eid:"21",
        ename: "Event 21",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-09-23',
        etime: "12:00",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "8",
        rname: "Mumbai",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'y',
      },
      {
        eid:"22",
        ename: "Event 22",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-09-23',
        etime: "14:00",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "8",
        rname: "Mumbai",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'y',
      },
      {
        eid:"23",
        ename: "Event 23",
        edesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        edate: '2022-09-23',
        etime: "01:00",
        eimg:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",
        rid: "8",
        rname: "Mumbai",    
        enp: "10",
        ewin: "ABC",
        elocation:"",
         evid:"",elikes:"2",
         estatus:'y',
      },
    ],
  
    regionalOffices: [
      {
        rstatus:'n',
        rid: 1,
        rimage:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",        
        rname: "Ahmedabad",
        rlocation: "Ahmedabad",
        rdesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      },
      {
        rstatus:'y',
        rid: 2,
        rimage:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",        
        rname: "Bengaluru",
        rlocation: "Bengaluru",
        rdesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      },
      {
        rstatus:'n',
        rid: 3,
        rimage:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",        
        rname: "Delhi University",
        rlocation: "Delhi",
        rdesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.", 
      },
      {
        rstatus:'y',
        rid: 4,
        rimage:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",        
        rname: "Guwahati",
        rlocation: "Guwahati",
        rdesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      },
      {
        rstatus:'n',
        rid: 5,
        rimage:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",        
        rname: "Jammu",
        rlocation: "Jammu",
        rdesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      },
      {
        rstatus:'y',
        rid: 6,
        rimage:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",        
        rname: "Kolkata",
        rlocation: "Kolkata",
        rdesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      },
      {
        rstatus:'n',
        rid: 7,
        rimage:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",        
        rname: "Lucknow",
        rlocation: "Lucknow",
        rdesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.", 
      },
      {
        rstatus:'y',
        rid: 8,
        rimage:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",        
        rname: "Mumbai",
        rlocation: "Mumbai",
        rdesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      },
      {
        rstatus:'n',
        rid: 9,
        rimage:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",        
        rname: "Patna",
        rlocation: "Patna",
        rdesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      },
      {
        rstatus:'y',
        rid: 10,
        rimage:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",        
        rname: "Pune",
        rlocation: "Pune",
        rdesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.", 
      },
      {
        rstatus:'n',
        rid: 11,
        rimage:"https://i.ytimg.com/vi/SiW8P42C0Ck/maxresdefault.jpg",        
        rname: "Shillong",
        rlocation: "Shillong",
        rdesc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.", 
      },
      
    ],
  
    
  };

  render() {
    return (
      <Context.Provider value={this.state}>
        {this.props.children}
      </Context.Provider>
    );
  }
}

export const Consumer = Context.Consumer;
